# -*- coding: utf-8 -*-
"""Jaat_Champion_2370300004.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j_chzQQIIMHQ4qFabiDtKiiV3oVt90k4
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.datasets import make_circles
import matplotlib.pyplot as plt
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten

import kagglehub

# Download latest version
path = kagglehub.dataset_download("berlinsweird/devanagari")

print("Path to dataset files:", path)

import os

# List files in the directory
print(os.listdir('/root/.cache/kagglehub/datasets/berlinsweird/devanagari/versions/3'))

import os
print(os.listdir('/root/.cache/kagglehub/datasets/berlinsweird/devanagari/versions/3/Hindi/'))

import os
print(os.listdir('/root/.cache/kagglehub/datasets/berlinsweird/devanagari/versions/3/Hindi/Train/'))
print(os.listdir('/root/.cache/kagglehub/datasets/berlinsweird/devanagari/versions/3/Hindi/Test/'))

# prompt: (x_train,y_train), (x_test,y_test) =   inport this data in this format

train_dir = '/root/.cache/kagglehub/datasets/berlinsweird/devanagari/versions/3/Hindi/Train/'
test_dir = '/root/.cache/kagglehub/datasets/berlinsweird/devanagari/versions/3/Hindi/Test/'

x_train = os.listdir(train_dir)
y_train = os.listdir(train_dir)

print(os.listdir(train_dir))
print(os.listdir(test_dir))

img_size = (32, 32)         # Image size

# Load training and test data with augmentation
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=10,
    zoom_range=0.1,
    width_shift_range=0.1,
    height_shift_range=0.1
)

test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=img_size,
    color_mode='grayscale',
    batch_size=32,
    class_mode='categorical'
)

test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=img_size,
    color_mode='grayscale',
    batch_size=32,
    class_mode='categorical'
)

from tensorflow.keras import models, layers, Input

model = models.Sequential([
    Input(shape=(32, 32, 1)),
    layers.Conv2D(32, (3,3), activation='relu'),
    layers.MaxPooling2D(2, 2),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),

    layers.Conv2D(128, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),

    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(train_generator.num_classes, activation='softmax')
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(
    train_generator,
    epochs=4,                           # Epochs only 4 ----  (iteration)
    validation_data=test_generator
)

model.evaluate(test_generator)
model.save("devanagari_cnn_model.h5")